#!/usr/bin/env node
/* eslint-disable no-console */
const { spawnSync } = require('node:child_process');

const result = spawnSync('corepack', ['pnpm', ...process.argv.slice(2)], { stdio: 'inherit' });
process.exit(result.status ?? 1);


